### ISSUE TITLE
Error: Thread was being aborted

### ISSUE THREAD

**Issue by Wesam18** [pauldambra/Serilog.Sinks.Network#7] opened 2016-12-12 16:26 UTC
I experienced log messages lost. The error message I received is "Error: Thread was being aborted. "

**Comment by pauldambra** [comment] 2016-12-12 16:54
Is this related to Issue 8? 

Can you share more details? Am using it in two prod apps with pretty high load now so definitely interested in sorting if this is lurking to bite us in the future!

**Comment by Wesam18** [comment] 2016-12-12 17:01
It is a different issue. This issue occurs when I didn't interact with the app for a while and when I start interacting with it again. the first several messages are not being streamed and instead I capture that error "Error: Thread is being aborted". The app with start working normally after that.

Note: The app is deployed in Azure Appservices

**Comment by pauldambra** [comment] 2016-12-14 20:54
TCP or UDP? We're using it in an Umbraco app that takes _forever_ to start from cold and haven't seen that before...

I've seen it in the past (iirc) with the rolling file logger when I'd managed to dispose of the logger and then tried to log to it. I'm wondering if something similar is happening here.

What type of app are you deploying? I haven't used azure app services so have no context

**Comment by Wesam18** [comment] 2016-12-14 20:58
I am using  TCP.

AppServices, is a service in Azure, where Azure control the underlying infrastructure and we just ship the package to be deployed so we have no control over the underlying infrastructure or machines.

check: https://azure.microsoft.com/en-us/services/app-service/

**Comment by pauldambra** [comment] 2016-12-14 21:00
Is it web api that you're deploying? Are you able to share your startup
code?

I can probably get some free time on Azure but would need to be able to
replicate the issue...

**Comment by Wesam18** [comment] 2016-12-14 21:06
I was testing by deploying that app 

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MVC%20Authentication

and I added this lines of code in the startup 

`           

Log.Logger = new LoggerConfiguration().MinimumLevel.Verbose()
                .WriteTo.TCPSink(URL, PORT_NUMBER)
                .CreateLogger();


`

**Comment by pauldambra** [comment] 2016-12-14 21:23
this startup?
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/MVC%20Authentication/Api/Startup.cs

**Comment by Wesam18** [comment] 2016-12-14 21:37
Yes.

**Comment by pauldambra** [comment] 2016-12-14 21:39
Cool. I'll try to make time the next couple of days.

I'll be turning on the self log
https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics to try
and see what is happening. If you want to do that first feel free.

Thanks for the other bug fix too!

P

**Comment by s1monfarrow** [comment] 2017-02-05 13:43
I'm also having issues using a TCP sink from within an azure app service. I was wondering if anyone had any insights. We had t working briefly but then it died and its not coming back. NLog doesn't seem to have any problems sending via tcp so I tried sending the debug output to nlog, got nothing so far. I'll post if I get anything more.

**Comment by pauldambra** [comment] 2017-02-05 13:51
@s1monfarrow if you can turn on the Serilog self log and pipe that out over nLog that would be awesome. My guess is that this is related to application start-up - the only time I've seen that message personally was with serilog file logger when I'd misunderstood how and when an application's start up code ran. So I'd like to rule that out or in...

https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

**Comment by s1monfarrow** [comment] 2017-02-05 15:03
I've just tried to get some logs out but failed. The last ones we made to get that made any reference to anything useful were:

System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 167.114.225.167:14990
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Serilog.Sinks.Network.Sinks.TCP.TcpSocketWriter.<>c__DisplayClass9_0.<.ctor>b__0(EndPoint h) in C:\projects\serilog-sinks-network\Serilog.Sinks.Network\Sinks\TCP\TCPSocketWriter.cs:line 77


Which looks like a timeout to me but might not be.

**Comment by pauldambra** [comment] 2017-02-05 15:08
It does... To ask the silly question: can you telnet to the endpoint?

**Comment by s1monfarrow** [comment] 2017-02-05 16:31
Yup and the logging works from my local machine just fine. It really looks like Azure is messing with something.

Simon

**Comment by s1monfarrow** [comment] 2017-02-05 20:05
I have found this since http://serverfault.com/questions/732008/outbound-packets-dropping-timeouts-only-with-azure I think this may be difficult to make work on azure.

**Comment by pauldambra** [comment] 2017-02-05 20:21
Possibly... I've used this extensively in AWS... maybe try UDP?

**Comment by s1monfarrow** [comment] 2017-02-05 20:42
I'm using the elastic sink for the minute, I'll move to http I think. I'm not looking to shove huge amounts of data through. I do think that this might be azure specific, I've been having issues with nlog over tcp as well.

**Comment by pauldambra** [comment] 2018-01-28 22:53
I'm going to close this as an Azure specific problem unless someone can provide reproduction details

**Closed by pauldambra** 2018-01-28 22:53 UTC
